### ISSUE TITLE
Readme contains maven example of configuration instead of gradle

### ISSUE THREAD

**Issue by si13b** [lgrignon/jsweet-gradle-plugin#1]
Hi!

The example in the readme of this repo gives an example of the plugin configuration, but it is in XML format (presumably for maven), instead of groovy.

I suggest something like the following:

```
apply plugin: 'org.jsweet.jsweet-gradle-plugin'

jsweet {
  targetVersion = EcmaScriptComplianceLevel.ES5
  bundle = false
  verbose = false
}
```

**Comment by lgrignon** [comment]
Hey Simon, yes you're totally right, I just forgot to replace the maven version, I will push a replacement example like yours soon.

Thanks :)

**Comment by si13b** [comment]
:+1: thanks!
