### ISSUE TITLE
Feature request: Extra Path config for node.js installation

### ISSUE THREAD

**Issue by philwilkinson** [lgrignon/jsweet-gradle-plugin#11]
I would like to be able to configure the node.js path in gradle.
see https://github.com/cincheo/jsweet/issues/347 for details.

**Comment by lgrignon** [comment]
I added this to JSweet Gradle plugin and deployed to 2.0.0-SNAPSHOT if you want to give a try.

Please tell me if it is ok for you and I will do it on maven plugin as well.

Thanks for your help

**Comment by philwilkinson** [comment]
Hi, yes i've modified the jsweet-examples project locally to work with jsweet-gradle-plugin 2.0.0-SNAPSHOT and gradle-node-plugin with the following configuration in build.gradle
```
afterEvaluate
{
	jsweet.setExtraSystemPath("${node.variant.nodeBinDir}")
}
```
and it all works perfectly.
Cheers. looking forward to rc2.

**Comment by lgrignon** [comment]
Great news :)
