### ISSUE TITLE
Latest snapshot can't be retrieved

### ISSUE THREAD

**Issue by amelnikoff** [lgrignon/jsweet-gradle-plugin#14]
Hi.
Gradle not able to load snapshot:

```
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.jsweet:jsweet-gradle-plugin:2.0.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve org.jsweet:jsweet-gradle-plugin:2.0.0-SNAPSHOT.
         > Could not get resource 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/jsweet-gradle-plugin/2.0.0-SNAPSHOT/jsweet-gradle-plugin-2.0.0-SNAPSHOT.pom'.
            > Could not HEAD 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/jsweet-gradle-plugin/2.0.0-SNAPSHOT/jsweet-gradle-plugin-2.0.0-SNAPSHOT.pom'. Received status code 409 from server: Conflict
```

**Comment by lgrignon** [comment]
Hi,
Seems that your local repository may be corrupted. Anyway, please try the versions used in the JSweet examples project:
https://github.com/cincheo/jsweet-examples/blob/master/build.gradle

Should do the trick for you.

**Comment by amelnikoff** [comment]
I tried to clean gradle cache, no luck.
Tried to call 
`gradle build --refresh-dependencies`
same result.

This is happens when you follow README.md from this project.

Build file from jsweet-examples seems to work.
But now I have another error:

```
> Task :jsweet FAILED
Cannot run program "node": error=2, No such file or directory
cannot find Node.js: install first and make sure that the 'node' command is in your execution path
cannot find node.js

```
Strange message, because I have installed node.

**Comment by lgrignon** [comment]
JSweet uses Node.js
http://www.jsweet.org/getting-started/

**Comment by amelnikoff** [comment]
False alarm, somehow I broke my PATH and it was without node and npm )

**Comment by lgrignon** [comment]
Haha, ok. Quick fix :) thanks
