### ISSUE TITLE
Minor feedback on what tasks depend on what

### ISSUE THREAD

**Issue by nedtwigg** [lgrignon/jsweet-gradle-plugin#15]
Minor feedback on [this snippet](https://github.com/lgrignon/jsweet-gradle-plugin/blob/77da8478eadeb87c12d434782dff6a150e9d45ff/src/main/java/org/jsweet/gradle/JSweetTranspileTask.java#L51).

1: It would be better to depend on `compileJava` rather than `classes`:

![](https://docs.gradle.org/current/userguide/img/javaPluginTasks.png)

2: It's easier to compose tasks in custom plugins if the tasks don't automatically create dependencies.  Probably the `JSweetPlugin` should add the dependency, rather than the task constructor.

**Comment by lgrignon** [comment]
Thanks for the feedback. Would you create a PR for this? I would merge it ASAP
