### ISSUE TITLE
The final version of plugin

### ISSUE THREAD

**Issue by mxmind** [lgrignon/jsweet-gradle-plugin#17]
Hi, 
I surfed on https://mvnrepository.com to find the stable final version of this plugin but found only the first release candidate. 
Do you have a plan to release given plugin with the final version?

**Comment by lgrignon** [comment]
Hello,
Actually the transpiler evolved a lot recently (many bug fixes / new cool features like async / await & ts transpilation optimization) so I think you should stick to the last snapshot version until we release the next release (2.2.0).

I did not upgrade / publish the gradle plugin to 2.2.0-SNAPSHOT, I will do this asap and tell you when done

**Comment by mxmind** [comment]
Thank you a lot

Сб, 26 трав. 2018 21:34 користувач Louis Grignon <notifications@github.com>
пише:

**Comment by lgrignon** [comment]
It should be up to date by now.
JSweet examples still not updated to this gradle plugin's version.

Please close if ok for you.
Bye
