### ISSUE TITLE
Module Resolution cannot be set by jsweet-gradle-plugin

### ISSUE THREAD

**Issue by orielmaute** [lgrignon/jsweet-gradle-plugin#18]
Module Resolution cannot be set by jsweet-gradle-plugin; please add feature to set the moduleResolution (i need npm instead of classic)

**Comment by lgrignon** [comment]
This is an easy one, would you try to add it here https://github.com/lgrignon/jsweet-gradle-plugin/blob/master/src/main/java/org/jsweet/gradle/JSweetTranspileTask.java#L134

and PR?

**Comment by lgrignon** [comment]
will be added to 3.0
