### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by tim777z** [lgrignon/jsweet-gradle-plugin#21]
**It seems the Maven Dependencies no longer exist**

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'SquareActivity'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jsweet:jsweet-gradle-plugin:2.0.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve org.jsweet:jsweet-gradle-plugin:2.0.0-SNAPSHOT.
         > Unable to load Maven meta-data from http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/jsweet-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/jsweet-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/jsweet-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 503 from server: Service Temporarily Unavailable
   > Could not resolve org.jsweet.jsweet-gradle-plugin:org.jsweet.jsweet-gradle-plugin.gradle.plugin:2.0.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve org.jsweet.jsweet-gradle-plugin:org.jsweet.jsweet-gradle-plugin.gradle.plugin:2.0.0-SNAPSHOT.
         > Unable to load Maven meta-data from http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/jsweet-gradle-plugin/org.jsweet.jsweet-gradle-plugin.gradle.plugin/2.0.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/jsweet-gradle-plugin/org.jsweet.jsweet-gradle-plugin.gradle.plugin/2.0.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/jsweet-gradle-plugin/org.jsweet.jsweet-gradle-plugin.gradle.plugin/2.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 503 from server: Service Temporarily Unavailable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 4s

**Comment by lgrignon** [comment]
Hello, 
We are facing a problem with our Maven repository. We are working on it and hope that everything will be back up & running by monday.

We are thinking of changing our repo strategy to avoid such problems in the future.
