### ISSUE TITLE
Should define its own sourceSet

### ISSUE THREAD

**Issue by vorth** [lgrignon/jsweet-gradle-plugin#22]
The plugin should define its own "jsweet" sourceSet, and only fall back to "main" if "jsweet" is absent.  In addition, the includes and excludes should be handled in the standard sourceSet fashion, not as configs of the JSweet plugin.

My use-case is a little odd: I'm building both a legacy Java project, and a JSweet-enabled web port, from the same sources.  This is effectively impossible without giving the two Gradle plugins different ways to select their sources from the same files.

**Comment by lgrignon** [comment]
Thanks @vorth 
This is indeed a good idea. 
Not sure if we have enough time to change this though, but will definitely try to do it!

**Comment by vorth** [comment]
I have made the change in a fork, but I did it on the 3.0 branch, which meant I had to switch from Java 8 to Java 11.  I’ll make it on the master, and submit a PR.

**Comment by lgrignon** [comment]
That's good news. Actually you can PR to 3.0 branch which is about to be released soon.
I will publish 3.0.0-RC4 version of the gradle plugin once your PR is merged

**Comment by lgrignon** [comment]
will be deployed with 2.4 and 3.0
