### ISSUE TITLE
Applying 'groovy' plugin for tests only yields a missing folder error

### ISSUE THREAD

**Issue by angexis** [lgrignon/jsweet-gradle-plugin#3]
```
apply plugin 'groovy'
apply plugin: 'org.jsweet.jsweet-gradle-plugin'
```

(I use 'groovy' only for tests using the spock framework)
=> 

```
> java.lang.IllegalStateException: basedir /home/jan/code/orientbase/src/main/groovy does not exist
```

workaround:

```
tasks.jsweet.setSources(sourceSets.getByName("main").getJava())
```

I will do a PR in a few days if you want, tonight is too late, and I have other things to finish...

**Comment by lgrignon** [comment]
Hello @angexis, did you take time to fix it?

**Comment by angexis** [comment]
Hello @lgrignon ! I think I had it fixed at that time but I did not do the PR... now the file was renamed and I'd have to redo and test it again... I had to temporarily suspend my off-work developing activity (I hope I will be able to resume soon!)... Basically the fix was to replace:
`sources.getSrcDirs();`
with
`sources.getAllJava().getSrcDirs(); 
`
This allows having more than just Java source dirs and leave them out of the transpiler which does not support those languages. Too bad I did not do the PR right away, my apologies about that.

**Comment by lgrignon** [comment]
Fixed because we filter on .java
