### ISSUE TITLE
Expose autoPropagateAsyncAwaits option for transpiler

### ISSUE THREAD

**Issue by HeithoffM** [lgrignon/jsweet-gradle-plugin#37]
For my purpose I need this option available in the gradle plugin. The transpiler already supports this option which actually works really well for me.

**Comment by lgrignon** [comment]
Hello. That would be a good idea. Would you want to give it a shot it a PR? I would review / mergr it quickly if you want

**Comment by HeithoffM** [comment]
@lgrignon Yes, that would be nice. Do you need to create a branch for that? I already have the coding done locally, including a version update and test fixing for missing jupiter dependencies ;)

**Comment by HeithoffM** [comment]
Thanks for the fast merging!
