### ISSUE TITLE
googlecode.com, release, plugins.gradle.org

### ISSUE THREAD

**Issue by Horcrux7** [lgrignon/jsweet-gradle-plugin#9]
I have some questions to your project?
- Why you need the repository from googlecode.com? I think this is dead?
- Do you plan a release? Or will be there a snapshot for ever?
- Do you plan to publish the plugin on plugins.gradle.org?

**Comment by lgrignon** [comment]
Hello, 
* We definitely want to remove this one, I will take a look
* I have to tag, push and release some versions, at least 1.2.x and 2.0.0 when ready but I need time for this. You can count on a 2.0.0 release which is the recommended version by september
* Not for now. Is it a blocking issue for you?

Thanks for your questions

**Comment by Horcrux7** [comment]
Thanks for the answers. No, it is not a blocker for me. But it is a simple signal for production ready. I have see in the meantime that all the candies also hosted on this repository. That its sounds like a must.

Repositories are coming and going like googlecode. That we does not like dependencies to such newcomers. We need stable build systems for many years.

**Comment by lgrignon** [comment]
Ok, thanks for your feedback. We will try to push it on central repo

**Comment by lgrignon** [comment]
@Horcrux7 you can use this release version which is published:
https://github.com/lgrignon/jsweet-gradle-plugin/releases/tag/2.0.0-rc1

or this one if you use 1.x branch:
https://github.com/lgrignon/jsweet-gradle-plugin/releases/tag/1.2.1

Btw I removed the googlecode.com repository in the last version.

I will create a dedicated issue for publishing to plugins.gradle.org
